### ISSUE TITLE
Retropad mapping switch not working

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/beetle-wswan-libretro#17]
@meepingsnesroms 

The retropad mapping is always the vertical one (dpad directions = buttons) right from the start.
Always map[1] gets applied never map[0] for some reason.

Since https://github.com/libretro/beetle-wswan-libretro/pull/16

**Comment by meepingsnesroms** [comment]
What platform?
I tested android and mac os and they both worked fine.

**Comment by meepingsnesroms** [comment]
Is it this:
`rotate_tall = !rotate_tall;`

Because when bool is defined as an unsigned char  != while bool is 0x1 will be 0xFE which is still non zero.

**Comment by Tatsuya79** [comment]
That's on windows 7 x64.
The orientation switching works so that's not it. 
It's just the control mapping.

**Comment by meepingsnesroms** [comment]
if(rotate_tall)
   {
      //upright rotation
      for (unsigned i = 0; i < MAX_BUTTONS; i++)
         input_buf |= map[1][i] != -1u &&
            input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, map[1][i]) ? (1 << i) : 0;
   }
   else
   {
      //normal rotation
      for (unsigned i = 0; i < MAX_BUTTONS; i++)
         input_buf |= map[0][i] != -1u &&
            input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, map[0][i]) ? (1 << i) : 0;
   }
This is how the input swap works, I dont see how rotation could work but not the keys?

**Comment by Tatsuya79** [comment]
If I replace your 1st line by

if (1)
{
//upright rotation
for (unsigned i = 0; i < MAX_BUTTONS; i++)
[...]

then it works and switches fine between control mappings... don't ask me why!

**Comment by meepingsnesroms** [comment]
If you turn off compiler optimization does it work the original way?

This looks like a compiler issue if it can change when a fixed number is controlling it.

**Comment by Tatsuya79** [comment]
OK forget it I'm confused. 🙍 
I was testing with a vertical game and expecting the dpad to act for movement in both orientations, that's stupid.

It works as intended: landscape game and vertical games are using the dpad and buttons when switched to their targetted ratio.
Sorry to have wasted your time.
