### ISSUE TITLE
[Wii U] Black screen when loading content

### ISSUE THREAD

**Issue by cucholix** [libretro/beetle-wswan-libretro#23]
The core loads just fine, but when loading a content it only display a black screen, it doesn't freeze the app though, I can exit to the menu back and forth.

The last working build:
- core: 1.6.9 WonderSwan v.0.9.35.1 415e97e
- RA GIT: (24-12-2017) 89bd389

First broken build:
- core: 1.7.0 WonderSwan v.0.9.35.1 fd18010
- RA GIT: (25-12-2017) 0a2b442

**Comment by retro-wertz** [comment]
this PR should probably work with Wii/WiiU too

https://github.com/libretro/beetle-wswan-libretro/pull/24
