### ISSUE TITLE
Update core to 1.23.0

### ISSUE THREAD

**Issue by ToniBC** [libretro/beetle-wswan-libretro#45]
Mednafen was recently updated with several corrections of this emulator and it would be nice to include them to improve those small errors. I don't know if some have already been applied, but since the core only reflects that it is in 0.9.35.1, they supposedly were not added.

After 0.9.35.1 this is what they changed:

- WonderSwan: Added experimental, undocumented support for interfacing with trap15's WonderFence program, which provides MobileWonderGate emulation; controlled via settings "wswan.excomm" and "wswan.excomm.path".  This support is currently only available on UN*X-like platforms.
- WonderSwan: Added SRAM size calculation for the raw header value of 0x05(used by MobileWonderGate).
- WonderSwan: Corrected the SRAM size calculation for the raw header value of 0x04(used by Dicing Knight and Judgement Silversword).
- WonderSwan: Rewrote RTC emulation code to avoid runtime use of C library time functions(fixing potential desync issues when using netplay and input-recording movies), and fixed the time initialization code to reflect the current local time instead of UTC.
- WonderSwan: Resolved a few compiler warnings.
- WonderSwan: Save/Load relevant WSR playback state in save states during WSR playback.
- WonderSwan: Add strict checking for proper save game memory file size on game load(NOTE: this will cause problems for Dicing Knight and Judgment Silversword save game memory files written with Mednafen versions prior to 0.9.36).
- WonderSwan: Added partial emulation(just enough to get it to work) of the WonderWitch's flash ROM, so that the WonderWitch firmware will boot now, and can be used with the "wswan.excomm" and "wswan.excomm.path" settings/functionality.
- WonderSwan: Removed erroneous constraints that were preventing opposing X* and Y* buttons from being pressed simultaneously, and changed the names of the the X* and Y* buttons used during input configuration, per tip from trap15.
- WonderSwan: Fixed off-by-1 bugs in window coordinate evaluation, per tip from trap15.
- WonderSwan: Fixed copyright notice headers to not allow distribution under versions of the GPL other than version 2(an oversight from back when the Cygne code was added to Mednafen).
- WonderSwan: Applied sound and DMA emulation fixes from trap15; fixes rain sound effect in "Star Hearts".  The changes did necessitate lowering the overall WonderSwan sound emulation volume a bit to prevent excessive clipping, however.
- WonderSwan: Removed setting "wswan.rotateinput", and added a new device("gamepadraa") that can be selected on virtual input port 1 to automatically rotate inputs when the display is rotated.

As always, thank you very much for the effort and this is only to remember that it is pending to update the core.

**Comment by f21red** [comment]
A lot got updated for this core. Phew.
https://github.com/libretro/beetle-wswan-libretro/pull/47

**Comment by ToniBC** [comment]
Thank you very much for updating it.
