### ISSUE TITLE
X-left isn't being assigned to any button.

### ISSUE THREAD

**Issue by ruijtunes** [libretro/beetle-wswan-libretro#52]
When I try to play a game using this core, everything runs fine but left isn't mapped to any button.
X-left isn't being assigned even if it displays it in the controls.

[retroarch__2020_01_04__09_49_26.log](https://github.com/libretro/beetle-wswan-libretro/files/4021743/retroarch__2020_01_04__09_49_26.log)

**Comment by tailshine** [comment]
Could be the endian issue again. It affects joypads and savestates. PR is sent so fingers crossed it's easy fix.

**Comment by ruijtunes** [comment]
I can confirm that it is already working correctly. Thanks.

**Comment by hizzlekizzle** [comment]
ok, i'll close this issue then.
