### ISSUE TITLE
.sav files defaulting to system directory even with savefile directory defined.

### ISSUE THREAD

**Issue by HerbFargus** [libretro/beetle-wswan-libretro#6]
I'm using a retroarch.cfg override (where I have a retroach.cfg file in folders by core) with retropie. I get the same results with --appendconfig

I've set the savefile directory to 

`savefile_directory = /home/pi/RetroPie/roms/saves/`

and savestate directory to

`savestate_directory = /home/pi/RetroPie/roms/states/`

The savestate directory seemed to work but the savefile directory did not, it always defaults to the system directory

This seems to be a common issue with most mednafen (Beetle) cores. 

See 

https://github.com/libretro/beetle-psx-libretro/issues/19

https://github.com/RetroPie/RetroPie-Setup/issues/1266

https://github.com/RetroPie/RetroPie-Setup/issues/1162

Based on this comment: https://github.com/libretro/beetle-psx-libretro/issues/19#issuecomment-173043158 It would likely would need to be done for all the Mednafen (beetle) cores.

**Comment by HerbFargus** [comment]
`savefile_directory` still needs to be sorted but at least now in game save files default to the rom folder instead of the system directory with https://github.com/libretro/beetle-wswan-libretro/pull/7

**Comment by sergiobenrocha2** [comment]
Issue is fixed, you can close it @twinaphex

**Comment by retro-wertz** [comment]
since core has been using the retro_get_memory_data/size already, this issue does not apply anymore...

**Comment by HerbFargus** [comment]
Thanks
