### ISSUE TITLE
Judgement Silversword - Rebirth Edition doesn't load

### ISSUE THREAD

**Issue by msheehan79** [libretro/beetle-wswan-libretro#75]
With Judgement Silversword - Rebirth Edition the first time it is loaded you see a brief status screen, then the ROM just opens to either a solid blue screen or flashes a bunch of random colors. Every subsequent attempt after that just goes straight to the flashing colors/blue screen.

Apparently there was a fix for this game on Mednafen 1.23.0 but I'm not sure if that update is backported to this core or not already?

Tested with 2 different Redump files:
Judgement Silversword - Rebirth Edition (Japan) (Rev 5C21)
Judgement Silversword - Rebirth Edition (Japan) (Rev 4321)

RetroArch 1.9.8
Beetle wswan build b631efb

![image](https://user-images.githubusercontent.com/1565622/135009020-80b1a6a3-a428-40c2-b7ab-218386293a25.png)

**Comment by MapleStoryPSN** [comment]
Chiming in to echo the same issue. Still not working.
