### ISSUE TITLE
Dicing Knight. not working

### ISSUE THREAD

**Issue by Denshadego** [libretro/beetle-wswan-libretro#76]
As the title says, after loading, the screen flashes indefinitely and the game does not start.
Tested with both a clean japanese and english patched roms, with previously created save files deleted just to be sure.

**Comment by Shotdie** [comment]
Same, doesn´t work, it crash instantly at the moment you try to start the game in the main menu

**Comment by MapleStoryPSN** [comment]
> Same, doesn´t work, it crash instantly at the moment you try to start the game in the main menu

Last known working core for both Judgment Silversword and Dicing Knight is from the stable 1.9.9 release of RetroArch. Just replace the current core with it and the games will work perfect again. You can grab it here: http://buildbot.libretro.com/stable/1.9.9/

**Comment by JaredNk** [comment]
> > Same, doesn´t work, it crash instantly at the moment you try to start the game in the main menu
> 
> Last known working core for both Judgement Silversword and Dicing Knight is from the stable 1.9.9 release of RetroArch. Just replace the current core with it and the games will work perfect again. You can grab it here: http://buildbot.libretro.com/stable/1.9.9/

Thanks !  👍😉

**Comment by Denshadego** [comment]
> > Same, doesn´t work, it crash instantly at the moment you try to start the game in the main menu
> 
> Last known working core for both Judgement Silversword and Dicing Knight is from the stable 1.9.9 release of RetroArch. Just replace the current core with it and the games will work perfect again. You can grab it here: http://buildbot.libretro.com/stable/1.9.9/

Is there an archive of that version of the core for android? I can't find one on the buildbot :(
